### PR TITLE
chore: Switch change management action to shared custom action

### PR DESCRIPTION
**Pull request by m-bodmer**
## Description

Switch to using the shared action in https://github.com/nrfta/action-change-management 

## How did you test the changes?

See that the change management action passes successfully

### CODE REVIEW

**Comment by josemarluedke** [comment]
Not sure what we need to change here, to allow the action to be executed as this repo is public.

**Comment by m-bodmer** [comment]
> Not sure what we need to change here, to allow the action to be executed as this repo is public.

Ah, right. We could probably make the change management action public.

**Comment by gjarmstrong** [comment]
This looks good to me. @josemarluedke, is there anything this PR needs?

**Comment by m-bodmer** [comment]
> This looks good to me. @josemarluedke, is there anything this PR needs?

Going to close this for now while we work on figuring out if we should make the private change management action public, or create a public version of it.

**Pull request closed without merging**
